# @package _global_

defaults:
  - override /algorithm: pointpatch_encoder_mango_decoder
  - override /dataset: bbv_v3

wandb:
  enabled: True

algorithm:
  edge_loss_weight: 20
  edge_loss_type: length

exp_name: 5404_bbv_pointpatch_encoder_mango_decoder


hydra:
  sweeper:
    grid_params:
      seed: 1003

