enable_loading: True  # general flag if loading is enabled
checkpoint: best   # Choose between "best" and "last", or specify an epoch (has to be one of the saved epochs)
root_path: ???  # path to the root of the experiment
output_path:  output/evaluations/paper_exp/trampoline_v4   
seeds: null
job_types: null
