# @package _global_

defaults:
  - override /algorithm: oracle_mgn
  - override /dataset: step_trampoline_v4


wandb:
  enabled: True

resume_from_checkpoint: True
old_exp_folder: "output/hydra/training/2026-04-24/5103_trampoline_v4_oracle_mgn/+ex_exp_v4=51_oracle_mgn,+pl=jsc_clusterduck"

exp_name: 5103d2_trampoline_v4_oracle_mgn


hydra:
  sweeper:
    grid_params:
      seed: 1001, 1002, 1003, 1004
