# @package _global_

defaults:
  - override /algorithm: ggns_trampoline
  - override /algorithm/optimizer: adamw
  - override /dataset: step_ggns_trampoline_v4


wandb:
  enabled: True

exp_name: 6801_trampoline_v4_ggns_noise_grid

seed: 1005
hydra:
  sweeper:
    grid_params:
      algorithm.input_mesh_noise: 0.001, 0.002, 0.005, 0.01
