# @package _global_

defaults:
  - override /algorithm: ggns_trampoline
  - override /algorithm/optimizer: adamw
  - override /dataset: step_ggns_trampoline_v4_realworld


wandb:
  enabled: True

algorithm:
  input_mesh_noise: 0.002

exp_name: 7802_trampoline_v4_ggns_realworld_seed_1002

hydra:
  sweeper:
    grid_params:
      seed: 1002
#      seed: 1003, 1004
