# @package _global_

defaults:
  - override /algorithm: dummy_mango_decoder
  - override /dataset: sd_v1

wandb:
  enabled: True

resume_from_checkpoint: True
old_exp_folder: "output/hydra/training/2026-04-24/5203_sd_dummy_mango_decoder/+ex_exp=52_dummy_mango_decoder,+pl=jsc_clusterduck"


exp_name: 5203d2_sd_dummy_mango_decoder


hydra:
  sweeper:
    grid_params:
      seed: 1001, 1002, 1003, 1004

