# @package _global_

defaults:
  - override /algorithm: pointpatch_encoder_mango_decoder_only_ml_and_matprop
  - override /dataset: sd_v1

wandb:
  enabled: True

exp_name: 6003d2_sd_pointpatch_encoder_mango_decoder_only_ml_and_matprop

resume_from_checkpoint: True
old_exp_folder: "output/hydra/training/2026-04-24/6003_sd_pointpatch_encoder_mango_decoder_only_ml_and_matprop/+ex_exp=60_pointpatch_encoder_mango_decoder_only_ml_and_matprop,+pl=jsc_clusterduck"


hydra:
  sweeper:
    grid_params:
      seed: 1001, 1002, 1003, 1004

