name: mgn
n_layers: 15
scatter_reduce: mean
activation: leakyrelu
use_hidden_layers: False
z_pos_feature: ${dataset.z_pos_feature}
latent_dimension: 128
output_decoder:
  latent_dimension: 128
  regularization:
    dropout: 0.0
  tanh:
    enabled: True
    scale_factor: 0.1
    input_scale_factor: 0.1

