# @package _global_

defaults:
  - override /algorithm: trampoline_pointpatch_encoder_mango_decoder
  - override /dataset: trampoline_v5

wandb:
  enabled: True

exp_name: 5405_trampoline_pointpatch_encoder_mango_decoder


hydra:
  sweeper:
    grid_params:
      seed: 1001, 1002, 1003, 1004

