name: bbv
wandb_name: bbv
root: ../datasets/pc_mango/bbv_v1.hdf5
z_pos_feature: False
cut_length: -1 # if -1, use all time steps, else only use the first cut_length time steps of each trajectory
temporal_stride: 4  # only use every nth time step, applied after cut_length

pc_preprocessing:
  output_type: tensor  # options: tensor, graph
  temporal_stride: 2
  num_subsample_points: 512  # null means no subsampling

train_dataset:
  root: ${dataset.root}
  cut_length: ${dataset.cut_length}
  temporal_stride: ${dataset.temporal_stride}
  batch_size: 1
  initial_vel: zero  # choose between zero and constant
  dataset_size: null  # artificially reduce dataset size for debugging
  random_traj_selection: True
  min_context_size: 1
  max_context_size: 8
  min_target_size: 1
  max_target_size: 1
  material_properties: ${algorithm.material_properties}
  material_properties_dim: 3 # poisson, viscosity, youngs_modulus
  data_modalities: ${algorithm.data_modalities}
  pc_preprocessing: ${dataset.pc_preprocessing}


eval_dataset:
  root: ${dataset.root}
  cut_length: ${dataset.cut_length}
  temporal_stride: ${dataset.temporal_stride}
  initial_vel: ${..train_dataset.initial_vel}
  dataset_size: null # artificially reduce dataset size for debugging
  random_traj_selection: False
  context_size: 4  # deterministic
  target_size: 10
  material_properties: ${..train_dataset.material_properties}
  material_properties_dim: 1
  data_modalities: ${..train_dataset.data_modalities}
  pc_preprocessing: ${..train_dataset.pc_preprocessing}
