# @package _global_

defaults:
  - override /algorithm: pointpatch_encoder_mango_decoder_only_ml_and_matprop
  - override /dataset: db_v4

wandb:
  enabled: True

exp_name: 6002_db_pointpatch_encoder_mango_decoder


hydra:
  sweeper:
    grid_params:
      seed: 1001, 1002, 1003, 1004

