"""Extract the hexbin plots of the latent-distance analysis (paper appendix) from the vector PDF.

figures/rsa_distances.pdf is a matplotlib figure with four hexbin panels (distance in physical
parameters rho vs. distance in the latent description r). Every hexagon is a vector path, so its
center can be mapped back to data coordinates via the tick positions, and its fill color can be
inverted exactly through matplotlib's "Blues" colormap into a relative density in [0, 1].

The page draws the hexagons itself (docs/static/js/main.js, initRsa) from
    docs/static/data/rsa_hexbins.json

Usage:  python tools/extract_rsa_hexbins.py <path/to/rsa_distances.pdf> [--out ...]
Requires pymupdf, numpy and matplotlib.
"""
import argparse
import json
from pathlib import Path

import numpy as np
import pymupdf
from matplotlib import colormaps

NAMES = ["Deforming Block", "Sheet Deformation", "Bending Beam", "Trampoline"]
SPEARMAN = [0.97, 0.96, 0.64, 0.60]  # Table "Correspondence between r and rho" in the appendix

# axes geometry of the PDF in points: x = 0 of each panel, pt per data unit, y = 0 baseline
X0 = [31.3, 121.7, 212.0, 302.4]
SX, Y0, SY = 25.1, 76.5, 23.5


def main(pdf, out):
    page = pymupdf.open(pdf)[0]
    lut = np.array([colormaps["Blues"](i / 255)[:3] for i in range(256)])
    panels = [[] for _ in X0]
    shape = None
    for d in page.get_drawings():
        if len(d["items"]) != 6 or not d.get("fill"):
            continue
        pts = np.array([[it[1].x, it[1].y] for it in d["items"]])
        cx, cy = pts.mean(axis=0)
        k = int(np.argmin([abs(cx - (x0 + 40)) for x0 in X0]))
        level = int(np.argmin(np.linalg.norm(lut - np.array(d["fill"]), axis=1)))
        if shape is None:  # hexagon vertex offsets in data units
            shape = [[round((px - cx) / SX, 4), round((cy - py) / SY, 4)] for px, py in pts]
        panels[k].append([round((cx - X0[k]) / SX, 4), round((Y0 - cy) / SY, 4), round(level / 255, 3)])
    data = {"about": "Generated by tools/extract_rsa_hexbins.py; density is relative (0..1).",
            "names": NAMES, "spearman": SPEARMAN, "hexagon": shape, "panels": panels}
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    Path(out).write_text(json.dumps(data, separators=(",", ":")))
    print(f"wrote {out}: {[len(p) for p in panels]} hexagons")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("pdf")
    ap.add_argument("--out", default="docs/static/data/rsa_hexbins.json")
    a = ap.parse_args()
    main(a.pdf, a.out)
