# @package _global_

defaults:
  - override /algorithm: ggns_trampoline
  - override /algorithm/optimizer: adamw
  - override /dataset: step_ggns_trampoline_v4_realworld


algorithm:
  input_mesh_noise: 0.002

wandb:
  enabled: True


dataset:
  train_dataset:
    save_to_disk: True
  eval_dataset:
    save_to_disk: True

exp_name: trampoline_v4_realworld_ggns_caching

hydra:
  sweeper:
    grid_params:
      seed: 1001
#      seed:  1002, 1003, 1004

